extends Node

var TranslationDict = {
	#Buildings
	WORKERMARKET = "Market",
	PURCHASE = "Purchase",
	TASKS = "Tasks",
	UPGRADES = "Upgrades",
	TOWNHALL = "Town Hall",
	FOODCONV = "Food Conversion",
	HARVESTMETAL = "Harvest Ore",
	HARVESTPLANT = "Harvest Plants",
	GOBLINWORKER = "Goblin Worker",
	ELVENWORKER = "Elven Worker",
	
	
	#Materials
	MATERIALWOOD = "Wood",
	MATERIALWOODDESCRIPT = "Sturdy wood for general building and furnishing purposes.",
	WOODADJ = "wooden",
	MATERIALSTONE = "Stone",
	MATERIALSTONEDESCRIPT = "Stone comes in many forms and shapes, but might serve as good building material or even poor instrumentum.",
	STONEADJ = 'stone',
	MATERIALELVENWOOD = "Elven Wood",
	MATERIALELVENWOODDESCRIPT = "An unusual wood with additional magic properties. ",
	ELVENWOODADJ = "Elven",
	MATERIALGOBLINMETAL = "Goblin Metal",
	METARIALGOBLINGMETALDESCRIPT = "Rusty looking metal, still decent for some work. Can be used for a heavy armor. ",
	GOBLINMETALADJ = "Goblin",
	MATERIALELVENMETAL = "Elven Metal",
	METARIALELVENMETALDESCRIPT = "Soft, but strong alloy storing some magic properties. ",
	ELVENMETALADJ = "Elven",
	MATERIALLETHER = "Leather",
	MATERIALLEATHERDESCRIPT = "A common animal leather. Can be used for a light armor.",
	LEATHERADJ = "Leather",
	MATERIALBONE = "Bone",
	MATERIALBONEDESCRIPT = "A common animal bone. With right approach can provide some interesting properties. ",
	BONEADJ = "Bone",
	MATERIALCLOTH = "Cloth",
	MATERIALCLOTHDESCRIPT = "A simple cotton fibre for simple clothes. Can be used for cloth armor. ",
	CLOTHADJ = "Cotton",
	
	
	#Items
	WEAPONAXENAME = "Axe",
	WEAPONPICKAXENAME = "Pickaxe",
	WEAPONSWORDNAME = 'Sword',
	WEAPONBOWNAME = "Bow",
	WEAPONSTAFFNAME = "Staff",
	
	
	WEAPONAXEDESCRIPT = 'Axe can be used for wood cutting and combat.',
	WEAPONSWORDDESCRIPT = "Good damage vs unarmored enemies.",
	WEAPONPICKAXEDESCRIPT = "Allows workers to harvest ore.",
	WEAPONBOWDESCRIPT = "Simple weapon for ranged fighters.",
	WEAPONSTAFFDESCRIPT = "A simple tool for magic users.",
	
	ARMORBASICCHEST = "Chestplate",
	ARMORROBE = "Robe",
	ARMORHOOD = "Hood",
	ARMORSHOES = "Shoes",
	ARMORBASICCHESTDESCRIPT = "Offers basic body protection.",
	ARMORBASICHELM = "Helmet",
	ARMORBASICHELMDESCRIPT = "Offers basic head protection.",
	ARMORBASICBOOTS = "Boots",
	ARMORBASICBOOTSDESCRIPT = "Offers basic foot protection",
	ARMORBASICGLOVES = "Gloves",
	ARMORBASICGLOVESDESCRIPT = "Offers basic hand protection",
	
	USABLEMORSEL = "Morsel",
	USABLEMORSELDESCRIPT = "A questionable piece of meat. Restores 50 health. Can be converted into Food.",
	
	#enemies
	MONSTERELVENRAT = "Elven Rat",
	MONSTERELVENRATFLAVOR = "These animals are fairly common in most areas. Distinct ears make them accumulate all sorts of moniker, but goblins seem to label them exactly this way...",
	MONSTERTREANT = "Ent",
	MONSTERTREANTFLAVOR = "Despite its looks, this thing is actually a plant. Often disguise itself as a simple trump for a nasty surprise.",
	MONSTERBIGTREANT = "Big Ent",
	MONSTERBIGTREANTFLAVOR = "Big ents are somewhat mobile and quite dangerous when provoked.",
	MONSTEREARTHGOLEM = "Earth Golem",
	MONSTEREARTHGOLEMFLAVOR = "A magic creature of considerable power. They seem to roam around some caves and dungeons with little thought. I would expect more from hand-made slave. ",
	MONSTERSPIDER = "Spider",
	MONSTERSPIDERFLAVOR = "Of course just ents weren't enough...",
	MONSTERFAIRIES = "Fairies",
	MONSTERFAIRIESFLAVOR = "If not for their nasty nature, I would even consider them appealing.",
	MONSTERANGRYDWARF = "Angry Dwarf",
	MONSTERANGRYDWARFFLAVOR = "Dumb but damn strong for their size. Despite my best attempts, they didn't seem to be up for any sort of negotiation. ",
	#gearclasses
	GEARSWORD = "Swords",
	GEARAXE = "Axes",
	GEARSTAFF = "Staves",
	GEARBOW = "Bows",
	
	#Stats
	DAMAGE = 'Damage',
	ARMOR = 'Armor',
	MDEF = "Magic Armor",
	EVASION = 'Evasion',
	HITRATE = 'Hit Chance',
	HEALTH = 'Health',
	DURABILITY = "Durability",
	DURABILITYMOD = "Dur. Factor",
	ARMORPENETRATION = "Armor Pen.",
	RESISTFIRE = "Fire Res.",
	RESISTEARTH = "Earth Res.",
	RESISTAIR = "Air Res.",
	RESISTWATER = "Water Res.",
	HEALTHPERCENT = "Max. Health",
	MANAPERCENT = "Max. Mana",
	CRITICAL = "Critical",
	CRITCHANCE = "Crit. Chance",
	CRITMOD = "Crit. Mod",
	LEVELUP = "Level up",
	LEVEUPTEXT = " has just acquired a level. Select a new trait to unlock",
	
	#stat tooltips
	TOOLTIPDAMAGE = "Defines damage output of skills and spells",
	TOOLTIPARMOR = "Reduces skill damage taken by this percent",
	TOOLTIPMDEF = "Reduces spell damage taken by this percent",
	TOOLTIPCRIT = "Percent chance to crit for extra damage\nFirst value is a chance. Second value is a modifier.",
	TOOLTIPHITRATE = "Percent chance to hit target\nReduced by enemy's evasion",
	TOOLTIPARMORPEN = "Reduces enemy armor by this value",
	TOOLTIPEVASION = "Reduces enemy hit chance by this value",
	TOOLTIPSPEED = "Improves your odds to act before other characters",
	TOOLTIPRESISTS = "Reduces elemental damage by relative resist",
	
	
	
	#Item Parts
	TOOLHANDLE = 'Handle',
	BLADE = 'Blade',
	BLUNT = 'Head',
	ROD = 'Knub',
	BOW = 'Bow Limb',
	ARMORBASE = 'Base',
	ARMORPLATE = 'Plate',
	ARMORTRIM = 'Trim',
	JEWELRYGEM = 'Gem',
	
	
	#Material Effects
	GOBMETALHANDLEDESCRIPT = "Deals 15% more damage when enemy's health below 30%",
	ELFMETALHANDLEDESCRIPT = "Gain +1 Mana on skill hit",
	GOBMETALBLADEDESCRIPT = "Deals small bonus earth damage",
	ELFMETALBLADEDESCRIPT = "Deals +10 damage on first hit",
	ELFWOODRODDESCRIPT = "Restores 10% mana on the end of combat",
	GOBMETALRODDESCRIPT = "For 1 turn reduces target's speed by 10 on spell hit",
	BONERODDESCRIPT = "Restores 3% health on spell hit",
	BONEBOWDESCRIPT = "+1 health on hit",
	
	
	#Menu
	NEWGAME = "New Game",
	LOAD = 'Load',
	OPTIONS = 'Options',
	QUIT = 'Quit',
	
	SOUND = "Sound",
	MUSIC = "Music",
	MASTERSOUND = "Master Volume",
	MUTE = "Mute",
	AUDIO = "Audio",
	
	TEXTSPEED = "Text Speed",
	SKIPREAD = "Skip Read",
	
	
	#System
	CONFIRM = "Confirm",
	CANCEL = "Cancel",
	NONE = "None",
	SPEED = "Speed",
	DAY = "Day",
	ENERGY = "Energy",
	TIME = "Time",
	CRAFT = "Craft",
	BLACKSMITH = "Blacksmith",
	REPAIR = "Repair",
	REPAIRALL = "Repair All",
	WORKERNOENERGY = " has no energy left and stopped working.",
	TOOLBROKEN = " has broken.",
	CURRENTTASK = "Current Task",
	REQUIREDMATERIAL = "Required Material",
	REQUIREDMATERIALS = "Required Materials",
	SELECTREPAIR = "Select Item(s) to Repair",
	TOTALPRICE = "Total Price",
	SELECTMATERIAL = "Select materials for all parts.",
	INPOSESSION = "In Possession",
	BASECHANCE = "Base Chance",
	CANTREPAIREFFECT = "This item can't be repaired.",
	NOTENOUGH = "Not enough",
	ITEMCREATED = "Item Created",
	UPGRADEUNLOCKED = "Upgrade Unlocked",
	MAINQUEST = "Main Quest",
	SIDEQUESTS = "Sidequests",
	MAINQUESTUPDATED = "Main Quest Updated",
	QUESTLOG = "Quest Log",
	NOACTIVEQUESTS = "You have no active quests.",
	INVALIDCLASS = "Invalid class for this gear.",
	NOTENOUGHGOLD = "Not enough gold",
	PURCHASETHISTRAIT = "Purchase this trait",
	TRAITPOINTSCOST = "Trait Points",
	TRAITPOINTS = "Trait Points used",
	GOLDPRICE = "Gold Cost",
	
	SELECTTOOL = "Select Tool",
	SELECTWORKER = "Select Worker",
	WORKERLIMITREACHER = "Worker Limit Reached: Upgrade Houses to increase",
	TOTALWORKERS = "Total Workers",
	
	TUTORIAL = "Tutorial",
	TRAITS = "Traits",
	CLASSINFO = "Class Details",
	
	INVENTORY = "Inventory",
	WORKERLIST = "Worker List",
	HEROLIST = "Hero List",
	OPTIONMENU = "Options",
	
	INVENTORYALL = "All items",
	INVENTORYWEAPON = "Weapons",
	INVENTORYARMOR = "Armor",
	INVENTORYMATERIAL = "Materials",
	INVENTORYUSE = "Usables",
	INVENTORYQUEST = "Misc",
	SELLCONFIRM = "Sell",
	RAWPRICE = "Raw Price",
	FOODDESCRIPT = "Food is used to feed workers. ",
	MONEYDESCRIPT = "Money are used to purchase goods and workers.",
	
	AREAISENDLESS = "This area has no progression",
	TOWNRETURN = "Return",
	
	#Confirms
	
	LEAVECONFIRM = "Leave to Main Menu? Unsaved progress will be lost. ",
	LOADCONFIRM = "Load this save file?",
	OVERWRITECONFIRM = "Overwrite this save file?",
	DELETECONFIRM = "Delete this save file?",
	STOPTASKCONFIRM = "Stop this job?",
	SLAVEREMOVECONFIRM = "Expel this worker?",
	
	
	#Inbuilt Tooltips
	PAUSEBUTTONTOOLTIP = 'Pause\nHotkey: 1',
	NORMALBUTTONTOOLTIP = 'Normal Speed\nHotkey: 2',
	FASTBUTTONTOOLTIP = 'Fast Speed\nHotkey: 3',
	
	
	#Tasks
	HARVESTWOOD = "Harvest Lumber",
	WOODCUTTINGTASKDESCRIPTION = "Harvest lumber from nearest vegetation",
	
	#Classes
	CLASSDESCRIPT = "Class defines character's basic characteristics, abilities, specific traits and allowed gear. More abilities are unlocked as you level up. After certain level you can advance into one of the new classes.",
	WARRIOR = "Warrior",
	MAGE = "Mage",
	ARCHER = "Archer",
	BRAWLER = "Brawler",
	WARRIORDESCRIPT = "Warrior is a strong melee class focusing on tanking and dealing damage. They can handle many weapons but lack in magic and range. ",
	MAGEDESCRIPT = "Mage is a supporting class capable of both healing and slinging powerful area spells. ",
	ARCHERDESCRIPT = "Archer is a ranged damaging class. Having access to some spells, they can hit any target on the battlefield. ",
	BRAWLERDESCRIPT = "Brawler is a melee supporting class. They specialize in using special attacks for crowd control. ",
	MAGETRAITDESCRIPT = "Gain 1 bonus Damage for every 2 bonus Magic Armor.",
	ARCHERTRAITDESCRIPT = "Gain 1 bonus Hit Rate for every 1 bonus Evasion.",
	CLASSALLOWEDWEAPONS = "Allowed gear",
	CLASSTRAIT = "Class bonus",
	
	#Names
	ARRON = 'Arron',
	ROSE = 'Rose',
	EMBER = 'Ember',
	GOBLIN = 'Goblin',
	GUARD1 = 'Guard1',
	GUARD2 = 'Guard2',
	GUARD3 = 'Guard3',
	NORBERT = 'Norbert',
	DEMITRIUS = "Demitrius",
	LYRA = "Lyra",
	FLAK = "Flak",
	
	#Skills
	SKILLATTACK = "Attack",
	SKILLATTACKDESCRIPT = "Attacks target with equipped weapon for %d damage. ",
	SKILLFIREBOLT = "Firebolt",
	SKILLFIREBOLTDESCRIPT = "Launches a fire spell on target. Deal %d Fire damage to all targets in same row.",
	SKILLWINDARROW = "Wind Arrow",
	SKILLWINDARROWDESCRIPT = "Imbues the arrow with Wind element and deal %d damage. Requires a bow equipped.",
	SKILLSLASH = "Slash",
	SKILLSLASHDESCRIPT = "Deals %d Weapon damage to all targets in nearby column. Requires a weapon equipped.",
	SKILLMINORHEAL = "Minor Heal",
	SKILLMINORHEALDESCRIPT = "Restore %d health of the target.",
	SKILLCONCENTRATE = "Concentrate",
	SKILLCONCENTRATEDESCRIPT = "Restore %d mana for self.",
	SKILLFIRESTORM = "Fire Storm",
	SKILLFIRESTORMDESCRIPT = "Deals %d fire damage to all enemies.",
	SKILLSTRONGSHOT = "Strong Shot",
	SKILLSTRONGSHOTDESCRIPT = "Deals %d Weapon damage to target enemy and stuns for 1 turn. Requires a bow equipped.",
	SKILLARROWSHOWER = "Arrow Shower",
	SKILLARROWSHOWERDESCRIPT = "Deals %d Weapon damage to all enemies.",
	SKILLTACKLE = "Tackle",
	SKILLTACKLEDESCRIPT = "Deals %d Physical damage and stuns target for 1 turn.",
	SKILLCRIPPLE = "Cripple",
	SKILLCRIPPLEDESCRIPT = "Deals %d Weapon damage and reduces target's damage for 3 turns.",
	SKILLCOMBOATTACK = "Combo Attack",
	SKILLCOMBOATTACKDESCRIPT = "Deals 3 consecutive hits for %d Weapon damage to target. ",
	
	
	
	#Upgrades
	UPGRADEPREVBONUS = "Current bonus",
	UPGRADENEXTBONUS = "Unlock bonus",
	BRIDGEUPGRADE = "Bridge",
	UPGRADEBRIDGEDESCRIPT = "Reinforce the bridge leading to the outer lands. Currently it barely allows locals move in and out, but you are afraid it might prove to dangerous for you to cross as is.",
	UPGRADEBRIDGEBONUS = "Unlocks exploration",
	MINEUPGRADE = "Mine",
	UPGRADEMINEDESCRIPT = "The old mine should still be rich in resources, but will require some work on it. ",
	UPGRADEMINEBONUS = "Allows production of ores.",
	FARMUPGRADE = "Farm",
	UPGRADEFARMDESCRIPT = "The farm allows cultivation of various plant fibers, useful for crafting. ",
	UPGRADEFARMBONUS = "Allows production of cloth",
	HOUSESUPGRADE = "Worker Barracks",
	UPGRADEHOUSESDESCRIPT = "Living quarters for your workers. ",
	UPGRADHOUSEBONUS1 = "Hosts up to 4 workers",
	UPGRADHOUSEBONUS2 = "Hosts up to 8 workers",
	BLACKSMITHUPGRADE = "Blacksmith",
	UPGRADEBLACKSMITHDESCRIPT = "Upgrade of Ember's forge will allow the production of new gear.",
	UPGRADEBLACKSMITHBONUS1 = "Unlocks Headgear",
	UPGRADEBLACKSMITHBONUS2 = "Unlocks footgear",
	LUMBERMILLUPGRADE = "Lumber mill",
	UPGRADELUMBERMILLDESCRIPT = "Improves the quality of Lumber Mill building.",
	UPGRADELUMBERMILLBONUS = "Increases the number of workers allowed in same time to 4. ",
	
	#traitdescriptions
	TRAITBEASTBONUSDAMAGE = "Deals 20% more damage to animals",
	TRAITBEASTBONUSRESIST = "Takes 20% less damage from animals",
	TRAITBEASTBONUSEXP = "Receive 15% more Experience after combat",
	TRAITBONUSHIT = "+10 Hit Rate",
	TRAITBONUSEVASION = "+10 Evasion",
	TRAITBONUSEVASIONPLUS = "+15 Evasion",
	TRAITBONUSCRIT = "+10% Critical Strike Chance",
	TRAITBONUSRESIST = "+10 To all elemental resists",
	TRAITBONUSARMOR = "+5 Armor",
	TRAITBONUSSPEED = "+10 Speed",
	TRAITBONUSHPMAX = "+25 Maximum Health",
	TRAITBONUSREGEN = "Regenerates 5% Health in the end of each turn",
	TRAITDODGEDEBUFF = "On hit: Reduces Enemy's evasion by 10 for 2 turns",
	TRAITGROUPARMOR = "+10 Armor to all characters in same row",
	TRAITDOUBLEHEAL = "When heals an ally, Caster also heals for 50% of effect",
	TRAITSPEEDONDAMAGE = "+20 Speed for 2 turns after taking damage",
	TRAITSPELLCRITBONUS = "Restores Spell's mana cost on Spell critical",
	TRAITSPEEDDEBUFF = "Reduces Speed and Evasion by 10 when hitting an enemy (stacks up to 2 times)",
	TRAITBOWEXTRADAMAGE = "After dealing a finishing blow, your next attack deals 100% more damage",
	TRAITCRITARMORIGNORE = "Critical strikes ignore target's Armor",
	TRAITDODGEGROUP = "+10 Speed to all characters on the same column",
	TRAITRESISTDEBUFF = "On hit reduces all target resists for 15 for 1 turn",
	TRAITFIREDAMAGEBONUS = "20% Extra Fire damage to skills",
	
	TAKEGOLDBUTTON = "Take Gold Instead",
	TAKEGOLDBUTTONTOOLTIP = "Refuse all traits and receive 100 gold"
}